"""add provider profiles and bookings

Revision ID: 893bb8bef81f
Revises: 675f13a89acc
Create Date: 2026-09-22 16:45:39.187787
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '893bb8bef81f'
down_revision: Union[str, None] = '675f13a89acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('resident_user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_user_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_provider_user_id'), ['provider_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_resident_user_id'), ['resident_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('provider_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_profiles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_provider_profiles_category'))

    op.drop_table('provider_profiles')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_resident_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_provider_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_category'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
