"""super admin email login: nullable mobile, password_hash

Revision ID: 94bc3a61a661
Revises: 893bb8bef81f
Create Date: 2026-09-22 18:31:44.459445
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94bc3a61a661'
down_revision: Union[str, None] = '893bb8bef81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
